//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Myapp.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Contract;

public interface Master extends com.zeroc.Ice.Object
{
    void calculatePi(int amountOfPoints, ClientPrx clientPrxCaller, com.zeroc.Ice.Current current);

    void reportFromWorkerPiWasCalculated(double amountOfpointsInsideTheCircle, String workerIdentifier, com.zeroc.Ice.Current current);

    String subToMaster(WorkerPrx workerPrxCaller, com.zeroc.Ice.Current current);

    void test(String s, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Contract::Master",
        "::Ice::Object"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::Contract::Master";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_calculatePi(Master obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_amountOfPoints;
        ClientPrx iceP_clientPrxCaller;
        iceP_amountOfPoints = istr.readInt();
        iceP_clientPrxCaller = ClientPrx.uncheckedCast(istr.readProxy());
        inS.endReadParams();
        obj.calculatePi(iceP_amountOfPoints, iceP_clientPrxCaller, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_reportFromWorkerPiWasCalculated(Master obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        double iceP_amountOfpointsInsideTheCircle;
        String iceP_workerIdentifier;
        iceP_amountOfpointsInsideTheCircle = istr.readDouble();
        iceP_workerIdentifier = istr.readString();
        inS.endReadParams();
        obj.reportFromWorkerPiWasCalculated(iceP_amountOfpointsInsideTheCircle, iceP_workerIdentifier, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_subToMaster(Master obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        WorkerPrx iceP_workerPrxCaller;
        iceP_workerPrxCaller = WorkerPrx.uncheckedCast(istr.readProxy());
        inS.endReadParams();
        String ret = obj.subToMaster(iceP_workerPrxCaller, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_test(Master obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_s;
        iceP_s = istr.readString();
        inS.endReadParams();
        obj.test(iceP_s, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "calculatePi",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "reportFromWorkerPiWasCalculated",
        "subToMaster",
        "test"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_calculatePi(this, in, current);
            }
            case 1:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 2:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 3:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 5:
            {
                return _iceD_reportFromWorkerPiWasCalculated(this, in, current);
            }
            case 6:
            {
                return _iceD_subToMaster(this, in, current);
            }
            case 7:
            {
                return _iceD_test(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
